package me.domino.fa2.ui.components

/** Fur Affinity Browse/Search 的分类选项（由页面导出的完整列表）。 */
object FaBrowseTaxonomyOptions {
  val categoryOptions: List<FilterOption<Int>> =
    listOf(
      FilterOption(1, "All"),
      FilterOption(34, "3D Models"),
      FilterOption(2, "Artwork (Digital)"),
      FilterOption(3, "Artwork (Traditional)"),
      FilterOption(4, "Cel Shading"),
      FilterOption(5, "Crafting"),
      FilterOption(6, "Designs"),
      FilterOption(32, "Food / Recipes"),
      FilterOption(8, "Fursuiting"),
      FilterOption(9, "Icons"),
      FilterOption(10, "Mosaics"),
      FilterOption(11, "Photography"),
      FilterOption(36, "Pixel Art"),
      FilterOption(12, "Sculpting"),
      FilterOption(35, "Virtual Photography"),
      FilterOption(37, "2D Animation"),
      FilterOption(38, "3D Animation"),
      FilterOption(39, "Pixel Animation"),
      FilterOption(7, "Flash"),
      FilterOption(40, "Interactive Media"),
      FilterOption(13, "Story"),
      FilterOption(14, "Poetry"),
      FilterOption(15, "Prose"),
      FilterOption(16, "Music"),
      FilterOption(17, "Podcasts"),
      FilterOption(18, "Skins"),
      FilterOption(19, "Handhelds"),
      FilterOption(20, "Resources"),
      FilterOption(21, "Adoptables"),
      FilterOption(22, "Auctions"),
      FilterOption(23, "Contests"),
      FilterOption(24, "Current Events"),
      FilterOption(25, "Desktops"),
      FilterOption(26, "Stockart"),
      FilterOption(27, "Screenshots"),
      FilterOption(28, "Scraps"),
      FilterOption(29, "Wallpaper"),
      FilterOption(30, "YCH / Sale"),
      FilterOption(31, "Other"),
    )

  val typeOptions: List<FilterOption<Int>> =
    listOf(
      FilterOption(1, "All"),
      FilterOption(2, "Abstract"),
      FilterOption(3, "Animal related (non-anthro)"),
      FilterOption(4, "Anime"),
      FilterOption(5, "Comics"),
      FilterOption(6, "Doodle"),
      FilterOption(7, "Fanart"),
      FilterOption(8, "Fantasy"),
      FilterOption(9, "Human"),
      FilterOption(10, "Portraits"),
      FilterOption(11, "Scenery"),
      FilterOption(12, "Still Life"),
      FilterOption(13, "Tutorials"),
      FilterOption(14, "Miscellaneous"),
      FilterOption(100, "General Furry Art"),
      FilterOption(122, "ABDL"),
      FilterOption(101, "Baby fur"),
      FilterOption(102, "Bondage"),
      FilterOption(103, "Digimon"),
      FilterOption(104, "Fat Furs"),
      FilterOption(105, "Fetish Other"),
      FilterOption(106, "Fursuit"),
      FilterOption(119, "Gore / Macabre Art"),
      FilterOption(107, "Hyper"),
      FilterOption(121, "Hypnosis"),
      FilterOption(108, "Inflation"),
      FilterOption(109, "Macro / Micro"),
      FilterOption(110, "Muscle"),
      FilterOption(111, "My Little Pony / Brony"),
      FilterOption(112, "Paw"),
      FilterOption(113, "Pokemon"),
      FilterOption(114, "Pregnancy"),
      FilterOption(115, "Sonic"),
      FilterOption(116, "Transformation"),
      FilterOption(120, "TF / TG"),
      FilterOption(117, "Vore"),
      FilterOption(118, "Water Sports"),
      FilterOption(201, "Techno"),
      FilterOption(202, "Trance"),
      FilterOption(203, "House"),
      FilterOption(204, "90s"),
      FilterOption(205, "80s"),
      FilterOption(206, "70s"),
      FilterOption(207, "60s"),
      FilterOption(208, "Pre-60s"),
      FilterOption(209, "Classical"),
      FilterOption(210, "Game Music"),
      FilterOption(211, "Rock"),
      FilterOption(212, "Pop"),
      FilterOption(213, "Rap"),
      FilterOption(214, "Industrial"),
      FilterOption(200, "Other Music"),
    )

  val speciesOptions: List<FilterOption<Int>> =
    listOf(
      FilterOption(1, "Unspecified / Any"),
      FilterOption(10001, "Airborne Vehicle"),
      FilterOption(5001, "Alien (Other)"),
      FilterOption(1000, "Amphibian (Other)"),
      FilterOption(2000, "Aquatic (Other)"),
      FilterOption(3000, "Avian (Other)"),
      FilterOption(6002, "Bear (Other)"),
      FilterOption(6007, "Bovine (Other)"),
      FilterOption(6017, "Canine (Other)"),
      FilterOption(6018, "Cervine (Other)"),
      FilterOption(6010, "Dog (Other)"),
      FilterOption(4000, "Dragon (Other)"),
      FilterOption(10009, "Equine (Other)"),
      FilterOption(5000, "Exotic (Other)"),
      FilterOption(6030, "Feline (Other)"),
      FilterOption(6075, "Fox (Other)"),
      FilterOption(10007, "Goo / Slime"),
      FilterOption(10002, "Hybrid Species"),
      FilterOption(10006, "Inanimate"),
      FilterOption(8003, "Insect (Other)"),
      FilterOption(10003, "Land Vehicle"),
      FilterOption(6000, "Mammal (Other)"),
      FilterOption(6042, "Marsupial (Other)"),
      FilterOption(6051, "Mustelid (Other)"),
      FilterOption(10008, "Plant / Fungus"),
      FilterOption(6058, "Primate (Other)"),
      FilterOption(7000, "Reptilian (Other)"),
      FilterOption(10004, "Robot / Android / Cyborg"),
      FilterOption(6067, "Rodent (Other)"),
      FilterOption(10005, "Sea Vehicle"),
      FilterOption(5025, "Taur (Other)"),
      FilterOption(6015, "Vulpine (Other)"),
      FilterOption(11014, "Original Species"),
      FilterOption(11015, "Fan Species / Character"),
      FilterOption(11001, "Aeromorph"),
      FilterOption(11002, "Angel Dragon"),
      FilterOption(11012, "Avali"),
      FilterOption(5003, "Chakat"),
      FilterOption(5005, "Citra"),
      FilterOption(5006, "Crux"),
      FilterOption(5009, "Dracat"),
      FilterOption(11003, "Dutch Angel Dragon"),
      FilterOption(11011, "Felkin"),
      FilterOption(11004, "Ferrin"),
      FilterOption(11005, "Jogauni"),
      FilterOption(5014, "Langurhali"),
      FilterOption(11006, "Nevrean"),
      FilterOption(11007, "Protogen"),
      FilterOption(11016, "Rexouium"),
      FilterOption(5021, "Sergal"),
      FilterOption(11010, "Synx"),
      FilterOption(11013, "Wickerbeast"),
      FilterOption(11009, "Yinglet"),
      FilterOption(11008, "Zorgoia"),
      FilterOption(12001, "Angel"),
      FilterOption(12002, "Centaur"),
      FilterOption(12003, "Cerberus"),
      FilterOption(12038, "Changeling / Shape Shifter"),
      FilterOption(12004, "Chimera"),
      FilterOption(12005, "Chupacabra"),
      FilterOption(12006, "Cockatrice"),
      FilterOption(5007, "Daemon"),
      FilterOption(12007, "Demon"),
      FilterOption(12008, "Displacer Beast"),
      FilterOption(12009, "Dragonborn"),
      FilterOption(12010, "Drow"),
      FilterOption(12011, "Dwarf"),
      FilterOption(4001, "Eastern Dragon"),
      FilterOption(5011, "Elf"),
      FilterOption(5012, "Gargoyle"),
      FilterOption(12012, "Goblin"),
      FilterOption(12013, "Golem"),
      FilterOption(3007, "Gryphon"),
      FilterOption(12014, "Harpy"),
      FilterOption(12015, "Hellhound"),
      FilterOption(12016, "Hippogriff"),
      FilterOption(12017, "Hobbit"),
      FilterOption(4002, "Hydra"),
      FilterOption(12018, "Imp"),
      FilterOption(12019, "Incubus"),
      FilterOption(12020, "Jackalope"),
      FilterOption(12021, "Kirin"),
      FilterOption(12022, "Kitsune"),
      FilterOption(12023, "Kobold"),
      FilterOption(12024, "Lamia"),
      FilterOption(12025, "Manticore"),
      FilterOption(12026, "Minotaur"),
      FilterOption(5016, "Naga"),
      FilterOption(12027, "Nephilim"),
      FilterOption(5018, "Orc"),
      FilterOption(12028, "Pegasus"),
      FilterOption(12029, "Peryton"),
      FilterOption(3010, "Phoenix"),
      FilterOption(12030, "Sasquatch"),
      FilterOption(5020, "Satyr"),
      FilterOption(12031, "Sphinx"),
      FilterOption(12032, "Succubus"),
      FilterOption(12033, "Tiefling"),
      FilterOption(12034, "Troll"),
      FilterOption(5023, "Unicorn"),
      FilterOption(12035, "Water Dragon"),
      FilterOption(12036, "Werewolf / Lycanthrope"),
      FilterOption(4004, "Western Dragon"),
      FilterOption(4005, "Wyvern"),
      FilterOption(12037, "Yokai"),
      FilterOption(13001, "Alicorn (MLP)"),
      FilterOption(5002, "Argonian"),
      FilterOption(13002, "Asari"),
      FilterOption(13003, "Bangaa"),
      FilterOption(13004, "Bubble Dragon"),
      FilterOption(13005, "Burmecian"),
      FilterOption(13006, "Charr"),
      FilterOption(13007, "Chiss"),
      FilterOption(5004, "Chocobo"),
      FilterOption(13008, "Deathclaw"),
      FilterOption(5008, "Digimon"),
      FilterOption(5010, "Draenei"),
      FilterOption(13009, "Drell"),
      FilterOption(13010, "Elcor"),
      FilterOption(13011, "Ewok"),
      FilterOption(13012, "Hanar"),
      FilterOption(13013, "Hrothgar"),
      FilterOption(5013, "Iksar"),
      FilterOption(5015, "Kaiju / Giant Monster"),
      FilterOption(13041, "Kelpie"),
      FilterOption(13014, "Kemonomimi"),
      FilterOption(13015, "Khajiit"),
      FilterOption(13016, "Koopa"),
      FilterOption(13017, "Krogan"),
      FilterOption(13018, "Lombax"),
      FilterOption(13019, "Mimiga"),
      FilterOption(13020, "Mobian"),
      FilterOption(5017, "Moogle"),
      FilterOption(13021, "Neopet"),
      FilterOption(13022, "Nu Mou"),
      FilterOption(5019, "Pokemon"),
      FilterOption(13023, "Pony (MLP)"),
      FilterOption(13024, "Protoss"),
      FilterOption(13025, "Quarian"),
      FilterOption(13026, "Ronso"),
      FilterOption(13027, "Salarian"),
      FilterOption(13028, "Sangheili / Elites"),
      FilterOption(13029, "Tauntaun"),
      FilterOption(13030, "Tauren"),
      FilterOption(13031, "Trandoshan"),
      FilterOption(13032, "Transformer"),
      FilterOption(13033, "Turian"),
      FilterOption(13034, "Twi'lek"),
      FilterOption(13035, "Viera"),
      FilterOption(13036, "Wookiee"),
      FilterOption(5024, "Xenomorph"),
      FilterOption(13037, "Yautja / Predator"),
      FilterOption(13038, "Yordle"),
      FilterOption(13039, "Yoshi"),
      FilterOption(13040, "Zerg"),
      FilterOption(14001, "Aardvark"),
      FilterOption(14002, "Aardwolf"),
      FilterOption(14003, "African Wild Dog"),
      FilterOption(14004, "Akita"),
      FilterOption(14005, "Albatross"),
      FilterOption(7001, "Alligator / Crocodile"),
      FilterOption(14006, "Alpaca"),
      FilterOption(14007, "Anaconda"),
      FilterOption(14008, "Anteater"),
      FilterOption(6004, "Antelope"),
      FilterOption(8000, "Arachnid"),
      FilterOption(14009, "Arctic Fox"),
      FilterOption(14010, "Armadillo"),
      FilterOption(14011, "Axolotl"),
      FilterOption(14012, "Baboon"),
      FilterOption(6045, "Badger"),
      FilterOption(6001, "Bat"),
      FilterOption(6064, "Beaver"),
      FilterOption(14013, "Bee"),
      FilterOption(14014, "Binturong"),
      FilterOption(14015, "Bison"),
      FilterOption(14016, "Blue Jay"),
      FilterOption(14017, "Border Collie"),
      FilterOption(14018, "Brown Bear"),
      FilterOption(14019, "Buffalo"),
      FilterOption(14020, "Buffalo / Bison"),
      FilterOption(14021, "Bull Terrier"),
      FilterOption(14022, "Butterfly"),
      FilterOption(14023, "Caiman"),
      FilterOption(6074, "Camel"),
      FilterOption(14024, "Capybara"),
      FilterOption(14025, "Caribou"),
      FilterOption(14026, "Caterpillar"),
      FilterOption(2001, "Cephalopod"),
      FilterOption(14027, "Chameleon"),
      FilterOption(6021, "Cheetah"),
      FilterOption(14028, "Chicken"),
      FilterOption(14029, "Chimpanzee"),
      FilterOption(14030, "Chinchilla"),
      FilterOption(14031, "Chipmunk"),
      FilterOption(14032, "Civet"),
      FilterOption(14033, "Clouded Leopard"),
      FilterOption(14034, "Coatimundi"),
      FilterOption(14035, "Cockatiel"),
      FilterOption(14036, "Corgi"),
      FilterOption(3001, "Corvid"),
      FilterOption(6022, "Cougar / Puma"),
      FilterOption(6003, "Cow"),
      FilterOption(6008, "Coyote"),
      FilterOption(14037, "Crab"),
      FilterOption(14038, "Crane"),
      FilterOption(14039, "Crayfish"),
      FilterOption(3002, "Crow"),
      FilterOption(14040, "Crustacean"),
      FilterOption(14041, "Dalmatian"),
      FilterOption(14042, "Deer"),
      FilterOption(14043, "Dhole"),
      FilterOption(6011, "Dingo"),
      FilterOption(8001, "Dinosaur"),
      FilterOption(6009, "Doberman"),
      FilterOption(2002, "Dolphin"),
      FilterOption(6019, "Donkey / Mule"),
      FilterOption(3003, "Duck"),
      FilterOption(3004, "Eagle"),
      FilterOption(14044, "Eel"),
      FilterOption(14045, "Elephant"),
      FilterOption(3005, "Falcon"),
      FilterOption(6072, "Fennec"),
      FilterOption(6046, "Ferret"),
      FilterOption(14046, "Finch"),
      FilterOption(2005, "Fish"),
      FilterOption(14047, "Flamingo"),
      FilterOption(14048, "Fossa"),
      FilterOption(1001, "Frog"),
      FilterOption(6005, "Gazelle"),
      FilterOption(7003, "Gecko"),
      FilterOption(14049, "Genet"),
      FilterOption(6012, "German Shepherd"),
      FilterOption(14050, "Gibbon"),
      FilterOption(6031, "Giraffe"),
      FilterOption(6006, "Goat"),
      FilterOption(3006, "Goose"),
      FilterOption(6054, "Gorilla"),
      FilterOption(14051, "Gray Fox"),
      FilterOption(14052, "Great Dane"),
      FilterOption(14053, "Grizzly Bear"),
      FilterOption(14054, "Guinea Pig"),
      FilterOption(14055, "Hamster"),
      FilterOption(3008, "Hawk"),
      FilterOption(6032, "Hedgehog"),
      FilterOption(14056, "Heron"),
      FilterOption(6033, "Hippopotamus"),
      FilterOption(14057, "Honeybee / Bumblebee"),
      FilterOption(6034, "Horse"),
      FilterOption(6020, "Housecat"),
      FilterOption(6055, "Human"),
      FilterOption(14058, "Humanoid"),
      FilterOption(14059, "Hummingbird"),
      FilterOption(6014, "Husky"),
      FilterOption(6035, "Hyena"),
      FilterOption(7004, "Iguana"),
      FilterOption(14060, "Impala"),
      FilterOption(6013, "Jackal"),
      FilterOption(6023, "Jaguar"),
      FilterOption(6038, "Kangaroo"),
      FilterOption(14061, "Kangaroo Mouse"),
      FilterOption(14062, "Kangaroo Rat"),
      FilterOption(14063, "Kinkajou"),
      FilterOption(14064, "Kit Fox"),
      FilterOption(6039, "Koala"),
      FilterOption(14065, "Kodiak Bear"),
      FilterOption(14066, "Komodo Dragon"),
      FilterOption(14067, "Labrador"),
      FilterOption(6056, "Lemur"),
      FilterOption(6024, "Leopard"),
      FilterOption(14068, "Liger"),
      FilterOption(14069, "Linsang"),
      FilterOption(6025, "Lion"),
      FilterOption(7005, "Lizard"),
      FilterOption(6036, "Llama"),
      FilterOption(14070, "Lobster"),
      FilterOption(14071, "Longhair Cat"),
      FilterOption(6026, "Lynx"),
      FilterOption(14072, "Magpie"),
      FilterOption(14073, "Maine Coon"),
      FilterOption(14074, "Malamute"),
      FilterOption(14075, "Mammal - Feline"),
      FilterOption(14076, "Mammal - Herd"),
      FilterOption(14077, "Mammal - Marsupial"),
      FilterOption(14078, "Mammal - Mustelid"),
      FilterOption(14079, "Mammal - Other Predator"),
      FilterOption(14080, "Mammal - Prey"),
      FilterOption(14081, "Mammal - Primate"),
      FilterOption(14082, "Mammal - Rodent"),
      FilterOption(14083, "Manatee"),
      FilterOption(14084, "Mandrill"),
      FilterOption(14085, "Maned Wolf"),
      FilterOption(8004, "Mantid"),
      FilterOption(14086, "Marmoset"),
      FilterOption(14087, "Marten"),
      FilterOption(6043, "Meerkat"),
      FilterOption(6048, "Mink"),
      FilterOption(14088, "Mole"),
      FilterOption(6044, "Mongoose"),
      FilterOption(14089, "Monitor Lizard"),
      FilterOption(6057, "Monkey"),
      FilterOption(14090, "Moose"),
      FilterOption(14091, "Moth"),
      FilterOption(6065, "Mouse"),
      FilterOption(14092, "Musk Deer"),
      FilterOption(14093, "Musk Ox"),
      FilterOption(1002, "Newt"),
      FilterOption(6027, "Ocelot"),
      FilterOption(14094, "Octopus"),
      FilterOption(14095, "Okapi"),
      FilterOption(14096, "Olingo"),
      FilterOption(6037, "Opossum"),
      FilterOption(14097, "Orangutan"),
      FilterOption(14098, "Orca"),
      FilterOption(14099, "Oryx"),
      FilterOption(14100, "Ostrich"),
      FilterOption(6047, "Otter"),
      FilterOption(3009, "Owl"),
      FilterOption(6052, "Panda"),
      FilterOption(14101, "Pangolin"),
      FilterOption(6028, "Panther"),
      FilterOption(14102, "Parakeet"),
      FilterOption(14103, "Parrot / Macaw"),
      FilterOption(14104, "Peacock"),
      FilterOption(14105, "Penguin"),
      FilterOption(14106, "Persian Cat"),
      FilterOption(6053, "Pig / Swine"),
      FilterOption(14107, "Pigeon"),
      FilterOption(14108, "Pika"),
      FilterOption(14109, "Pine Marten"),
      FilterOption(14110, "Platypus"),
      FilterOption(14111, "Polar Bear"),
      FilterOption(6073, "Pony"),
      FilterOption(14112, "Poodle"),
      FilterOption(14113, "Porcupine"),
      FilterOption(2004, "Porpoise"),
      FilterOption(14114, "Procyonid"),
      FilterOption(14115, "Puffin"),
      FilterOption(6040, "Quoll"),
      FilterOption(6059, "Rabbit / Hare"),
      FilterOption(6060, "Raccoon"),
      FilterOption(6061, "Rat"),
      FilterOption(14116, "Ray"),
      FilterOption(14117, "Red Fox"),
      FilterOption(6062, "Red Panda"),
      FilterOption(14118, "Reindeer"),
      FilterOption(14119, "Reptillian"),
      FilterOption(6063, "Rhinoceros"),
      FilterOption(14120, "Robin"),
      FilterOption(14121, "Rottweiler"),
      FilterOption(14122, "Sabercats"),
      FilterOption(14123, "Sabertooth"),
      FilterOption(1003, "Salamander"),
      FilterOption(8005, "Scorpion"),
      FilterOption(14124, "Seagull"),
      FilterOption(14125, "Seahorse"),
      FilterOption(6068, "Seal"),
      FilterOption(14126, "Secretary Bird"),
      FilterOption(4003, "Serpent Dragon"),
      FilterOption(14127, "Serval"),
      FilterOption(2006, "Shark"),
      FilterOption(14128, "Sheep"),
      FilterOption(14129, "Shiba Inu"),
      FilterOption(14130, "Shorthair Cat"),
      FilterOption(14131, "Shrew"),
      FilterOption(14132, "Siamese"),
      FilterOption(14133, "Sifaka"),
      FilterOption(14134, "Silver Fox"),
      FilterOption(6069, "Skunk"),
      FilterOption(14135, "Sloth"),
      FilterOption(14136, "Snail"),
      FilterOption(7006, "Snake / Serpent"),
      FilterOption(14137, "Snow Leopard"),
      FilterOption(14138, "Sparrow"),
      FilterOption(14139, "Squid"),
      FilterOption(6070, "Squirrel"),
      FilterOption(14140, "Stoat"),
      FilterOption(14141, "Stork"),
      FilterOption(14142, "Sugar Glider"),
      FilterOption(14143, "Sun Bear"),
      FilterOption(3011, "Swan"),
      FilterOption(14144, "Swift Fox"),
      FilterOption(5022, "Tanuki"),
      FilterOption(14145, "Tapir"),
      FilterOption(14146, "Tasmanian Devil"),
      FilterOption(14147, "Thylacine"),
      FilterOption(6029, "Tiger"),
      FilterOption(14148, "Toucan"),
      FilterOption(7007, "Turtle / Tortoise"),
      FilterOption(14149, "Vulture"),
      FilterOption(6041, "Wallaby"),
      FilterOption(14150, "Walrus"),
      FilterOption(14151, "Wasp"),
      FilterOption(6049, "Weasel"),
      FilterOption(2003, "Whale"),
      FilterOption(6016, "Wolf"),
      FilterOption(6050, "Wolverine"),
      FilterOption(6071, "Zebra"),
    )

  val typeOptionGroups: List<FilterOptionGroup<Int>> =
    listOf(
        FilterOptionGroup(
          label = "General Things",
          options =
            sliceByLabel(options = typeOptions, startLabel = "All", endLabel = "Miscellaneous"),
        ),
        FilterOptionGroup(
          label = "Specialty",
          options =
            sliceByLabel(
              options = typeOptions,
              startLabel = "General Furry Art",
              endLabel = "Water Sports",
            ),
        ),
        FilterOptionGroup(
          label = "Music",
          options =
            sliceByLabel(options = typeOptions, startLabel = "Techno", endLabel = "Other Music"),
        ),
      )
      .filter { group -> group.options.isNotEmpty() }

  val speciesOptionGroups: List<FilterOptionGroup<Int>> =
    listOf(
        FilterOptionGroup(
          label = "",
          options =
            sliceByLabel(
              options = speciesOptions,
              startLabel = "Unspecified / Any",
              endLabel = "Unspecified / Any",
            ),
        ),
        FilterOptionGroup(
          label = "General",
          options =
            sliceByLabel(
              options = speciesOptions,
              startLabel = "Airborne Vehicle",
              endLabel = "Vulpine (Other)",
            ),
        ),
        FilterOptionGroup(
          label = "Fandom Creations",
          options =
            sliceByLabel(
              options = speciesOptions,
              startLabel = "Original Species",
              endLabel = "Zorgoia",
            ),
        ),
        FilterOptionGroup(
          label = "Mythological / Fantasy",
          options = sliceByLabel(options = speciesOptions, startLabel = "Angel", endLabel = "Yokai"),
        ),
        FilterOptionGroup(
          label = "Games / Media",
          options =
            sliceByLabel(options = speciesOptions, startLabel = "Alicorn (MLP)", endLabel = "Zerg"),
        ),
        FilterOptionGroup(
          label = "Animal Kingdom",
          options =
            sliceByLabel(options = speciesOptions, startLabel = "Aardvark", endLabel = "Zebra"),
        ),
      )
      .filter { group -> group.options.isNotEmpty() }

  private val normalizedCategoryLabelToId: Map<String, Int> = categoryOptions.associate {
    normalizeLabel(it.label) to it.value
  }

  private val normalizedTypeLabelToId: Map<String, Int> = typeOptions.associate {
    normalizeLabel(it.label) to it.value
  }

  private val normalizedSpeciesLabelToId: Map<String, Int> = speciesOptions.associate {
    normalizeLabel(it.label) to it.value
  }

  fun findCategoryIdByLabel(label: String): Int? =
    normalizedCategoryLabelToId[normalizeLabel(label)]

  fun findTypeIdByLabel(label: String): Int? = normalizedTypeLabelToId[normalizeLabel(label)]

  fun findSpeciesIdByLabel(label: String): Int? = normalizedSpeciesLabelToId[normalizeLabel(label)]

  private fun sliceByLabel(
    options: List<FilterOption<Int>>,
    startLabel: String,
    endLabel: String,
  ): List<FilterOption<Int>> {
    val startIndex = options.indexOfFirst { option -> option.label == startLabel }
    val endIndex = options.indexOfFirst { option -> option.label == endLabel }
    if (startIndex < 0 || endIndex < 0 || endIndex < startIndex) return emptyList()
    return options.subList(startIndex, endIndex + 1)
  }

  private fun normalizeLabel(label: String): String =
    label.trim().lowercase().replace(Regex("\\s+"), " ")
}
